### ISSUE TITLE
Hcaptcha 

### ISSUE THREAD

**Issue by centipedex** [Its-Vichy/RevoltGenerator#6]
it says hcaptcha is not a module, when i install the library it says unable to access. could anyone help?

**Comment by Mewzax** [comment]
> it says hcaptcha is not a module, when i install the library it says unable to access. could anyone help?

hcaptcha library has been deleted

**Comment by centipedex** [comment]
> > it says hcaptcha is not a module, when i install the library it says unable to access. could anyone help?
> 
> hcaptcha library has been deleted

yeah, i knew that much

**Comment by Nostorian** [comment]
> it says hcaptcha is not a module, when i install the library it says unable to access. could anyone help?

`pip install django-hcaptcha`
use this instead, for reference you can check it in the website [here](https://pypi.org/project/django-hCaptcha/)

**Comment by Its-Vichy** [comment]
lmfao, learn to read lib is on github not on pypi
